name: Build EntrySafe Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install pyinstaller
          pip install opencv-python
          pip install face_recognition
          pip install PyQt6
          pip install psycopg2-binary

      - name: Build EXE with PyInstaller
        shell: pwsh
        run: |
          pyinstaller --noconsole --onedir --name EntrySafe `
            --paths . `
            --hidden-import views `
            --hidden-import utils `
            --collect-submodules views `
            --collect-submodules utils `
            --add-data "assets;assets" `
            --add-data "ui;ui" `
            --add-data "uploads;uploads" `
            --add-data "config.json;." `
            main.py


      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: EntrySafe-Windows-Build
          path: dist/EntrySafe
